[package]
name = "aw-watcher-sway"
version = "0.1.0"
authors = ["Johan Bjäreholt <johan@bjareho.lt>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
serde_json = "1.0"
aw_client_rust = { git = "https://github.com/ActivityWatch/aw-client-rust.git" }
chrono = "0.4"
